version: "3"
services:
  app:
    image: cpp-dev-env:latest
    build:
        context: .
        dockerfile: Dockerfile
        target: build
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
